# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fdbf840a7d2697ca36a1ee27344ce85deae40fac1609bb7bc8ce1ea28fd6fa4e474536e09f55c8f41e10b66c8758755d8d02c53595aef1e1a431b82d0cd8a10

test:
  secret_key_base: 088da6d2f2b78319fffc80bbd1708ae7ee67f2204209b0175880a5e8fc813d7690d75af6cb8b5fdcf0e328195d0229826567e0951aadfc5938583ea44aedfde8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
